name: .NET Build and Test CI

on:
  pull_request:
    branches:
      - '*'  # This will trigger the action on pull requests to any branch

jobs:
  build-and-test:
    runs-on: windows-latest  # You can specify other environments like windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x' # Specify the .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal
